from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOC_PATH = ROOT / "TOC.md"

IGNORE_NAMES = {
    ".git",
    "__pycache__",
    ".DS_Store",
    "node_modules",
    ".venv",
    "venv",
}
SKIP_FILES = {".gitkeep"}

ROOT_DESCRIPTIONS = {
    ".github/": "lightweight repo automation, including TOC maintenance",
    "README.md": "core-first repo overview and boundary rules",
    "TOC.md": "current auto-generated repository map",
    "cases/": "reference, demo, and smoke case material",
    "engine/": "canonical GFE source texts",
    "privacy.html": "privacy page required by the GPT custom action connector",
    "product/": "quarantined product area for new GUI/app work",
    "scripts/": "small repo maintenance scripts",
    "solver/": "executable solver core and validation implementation",
    "users/DEV/": "DEV-local tools and surviving migration references",
}

PRODUCT_DESCRIPTIONS = {
    "product/gui/": "user-facing GUI surfaces and presentation modules",
    "product/app/": "app-level loading, state, and runtime wiring",
    "product/assets/": "static product-local assets",
    "product/workflows/": "product-local workflow notes and templates",
}

DEV_DESCRIPTIONS = {
    "users/DEV/DEV-Tools/": "narrow helper tools, operating notes, and handoff assets",
    "users/DEV/REPOprojects/": "surviving project notes and migration references",
}


def include_path(path: Path) -> bool:
    if path.name in IGNORE_NAMES:
        return False
    if path.is_file() and path.name in SKIP_FILES:
        return False
    return True


def sorted_children(path: Path):
    children = [child for child in path.iterdir() if include_path(child)]
    return sorted(children, key=lambda child: (0 if child.is_dir() else 1, child.name.lower()))


def tree_lines(path: Path, prefix: str = ""):
    children = sorted_children(path)
    lines = []

    for index, child in enumerate(children):
        connector = "└── " if index == len(children) - 1 else "├── "
        label = f"{child.name}/" if child.is_dir() else child.name
        lines.append(f"{prefix}{connector}{label}")
        if child.is_dir():
            extension = "    " if index == len(children) - 1 else "│   "
            lines.extend(tree_lines(child, prefix + extension))

    return lines


def bullet_lines(description_map):
    lines = []
    for key, description in description_map.items():
        path = ROOT / key.rstrip("/")
        if path.exists():
            lines.append(f"- `{key}` — {description}")
    return lines


def render_toc() -> str:
    lines = [
        "# Repository TOC",
        "",
        "> Auto-generated by `scripts/update_toc.py` and kept current by `.github/workflows/update-toc.yml`.  ",
        "> Placeholder `.gitkeep` files are omitted. Do not edit by hand.",
        "",
        "## Key areas",
        "",
        *bullet_lines(ROOT_DESCRIPTIONS),
        "",
        "## Product work areas",
        "",
        *bullet_lines(PRODUCT_DESCRIPTIONS),
        "",
        "## DEV reference areas",
        "",
        *bullet_lines(DEV_DESCRIPTIONS),
        "",
        "## Full tree",
        "",
        "```text",
        ".",
        *tree_lines(ROOT),
        "```",
        "",
    ]
    return "\n".join(lines)


def main():
    TOC_PATH.write_text(render_toc(), encoding="utf-8")


if __name__ == "__main__":
    main()
